// router
export const CHANGE_VIEW = "CHANGE_VIEW"
export const BACK_TO_PREVIOUS_VIEW = "BACK_TO_PREVIOUS_VIEW"

// title
export const CHANGE_TEXT_COLOR = "CHANGE_TEXT_COLOR"
export const CHANGE_TEXT_TO_WHITE = "CHANGE_TEXT_TO_WHITE"
export const CHANGE_TEXT_TO_BLACK = "CHANGE_TEXT_TO_BLACK"

// current goal
export const CHANGE_GOAL = "CHANGE_GOAL"
export const SELECT_DAY = "TOGGLE_SELECT_DAY"
export const SET_START_DATE = "SET_START_DATE"
export const SET_SCHEDULED_FINISH_DATE = "SET_SCHEDULED_FINISH_DATE"
export const SET_ACTUAL_FINISH_DATE = "SET_ACTUAL_FINISH_DATE"
export const SET_DURATION = "SET_DURATION"
export const SELECT_TIME_OF_DAY = "SELECT_TIME_OF_DAY"
export const CHANGE_TIME = "CHANGE_TIME"
export const CHANGE_TECHNIQUES = "CHANGE_TECHNIQUES"
export const CLEAR_CURRENT_GOAL = "CLEAR_CURRENT_GOAL"

// technique
export const TOGGLE_SELECT_TECHNIQUE = "TOGGLE_SELECT_TECHNIQUE"

// profile
export const CHANGE_NAME = "CHANGE_NAME"
export const CHANGE_AVATAR = "CHANGE_AVATAR"
export const CLEAR_WELCOME_SCREEN = "CLEAR_WELCOME_SCREEN"
export const SET_LOGGED_ON_DATE = "SET_LOGGED_ON_DATE"
export const SET_DAILY_QUOTE = "SET_DAILY_QUOTE"

//previous goals
export const ARCHIVE_GOAL = "ARCHIVE_GOAL"

// tips
export const SELECT_TOPIC = "SELECT_TOPIC"
export const SET_PAGE_INDEX = "SET_PAGE_INDEX"

// staticData
export const ADD_QUOTES_DATA = "ADD_QUOTES_DATA"

//bot
export const SAVE_BOT_STATE = "SAVE_BOT_STATE"

//versions
export const UPGRADE_V2 = "UPGRADE_V2"
