// router
export const CHANGE_VIEW = "CHANGE_VIEW"
export const REDIRECT_TO_CODE = "REDIRECT_TO_CODE"
export const REDIRECT_TO_HOME = "REDIRECT_TO_HOME"

// code
export const VERIFY_SUCCESSED = "VERIFY_SUCCESSED"
export const VERIFY_FAILED = "VERIFY_FAILED"

// title
export const CHANGE_TEXT_COLOR = "CHANGE_TEXT_COLOR"
export const CHANGE_TEXT_TO_WHITE = "CHANGE_TEXT_TO_WHITE"
export const CHANGE_TEXT_TO_BLACK = "CHANGE_TEXT_TO_BLACK"
