// router
export const CHANGE_VIEW = "CHANGE_VIEW"
export const BACK_TO_PREVIOUS_VIEW = "BACK_TO_PREVIOUS_VIEW"

// code
export const VERIFY_SUCCEEDED = "VERIFY_SUCCEEDED"
export const VERIFY_FAILED = "VERIFY_FAILED"
export const VERIFY_START = "VERIFY_START"
export const VERIFY_FAILED_ROLLBACK = "VERIFY_FAILED_ROLLBACK"

// title
export const CHANGE_TEXT_COLOR = "CHANGE_TEXT_COLOR"
export const CHANGE_TEXT_TO_WHITE = "CHANGE_TEXT_TO_WHITE"
export const CHANGE_TEXT_TO_BLACK = "CHANGE_TEXT_TO_BLACK"

// current goal
export const CHANGE_GOAL = "CHANGE_GOAL"
export const SELECT_DAY = "TOGGLE_SELECT_DAY"
export const SET_START_DATE = "SET_START_DATE"
export const SET_FINISH_DATE = "SET_FINISH_DATE"
export const SET_DURATION = "SET_DURATION"
export const SELECT_TIME_OF_DAY = "SELECT_TIME_OF_DAY"
export const CHANGE_TIME = "CHANGE_TIME"
export const CHANGE_TECHNIQUES = "CHANGE_TECHNIQUES"

// technique
export const TOGGLE_SELECT_TECHNIQUE = "TOGGLE_SELECT_TECHNIQUE"

// profile
export const CHANGE_NAME = "CHANGE_NAME"
export const CHANGE_AVATAR = "CHANGE_AVATAR"
